### PR TITLE
Add zsh port

### PR DESCRIPTION
**Pull request by qfjp**
I made some minor changes to your script for a zsh port. It's uploaded as a new file, but if you diff them the changes are small. The most drastic change I had to make is changing the variable name 'path' to 'lpath', since path and PATH are linked in zsh

### CODE REVIEW

**Comment by shyiko** [comment]
:+1: I'll test it and get back to you. Thank you!

**Comment by shyiko** [comment]
Okay, unless I'm missing something - it does not work. Tried "mkdir -p /tmp/x/y/z && cd /tmp/x" -> source commacd.zsh -> 

```sh
% , y
_commacd_expand: unknown file attribute: y
_commacd_forward_by_prefix:1: no matches found: matches=()
_commacd_forward:3: no matches found: dir=()
% ,, tm
_commacd_expand: number expected
_commacd_expand: number expected
/tmp/x
```

**Comment by qfjp** [comment]
I can't reproduce those errors, do  you have any shell options set in your zshrc? I just tried with a clean configuration and it is working for me. Also, I'm using zsh v5.1.1.

Here's what I'm seeing, for reference
https://asciinema.org/a/7igeedoqnubmj8y4y1xsokd9z

**Comment by shyiko** [comment]
I specifically removed ~/.zshrc before testing ZSH version out (zsh 5.0.5 (x86_64-apple-darwin13.0.0)). Anyway, if it works for you - then the problem is definitely on my side. I'll figure it out. Thank you.

**Comment by shyiko** [comment]
Alright, port does not work on zsh < 5.1.0 (local declarations have to be on a separate line, expansions have to be rewritten from ${!...} to ${(k)...}, etc). Considering that 5.1.0 came out on 2015-09-01 I would prefer to have a port that supports all 5.X.X releases just to avoid numerous bug reports. Also, it would be real nice if we could preserve tab completion.

**Comment by qfjp** [comment]
Should be compatible with older versions of zsh now. 

I don't know any way to make the completions work without resorting to a separate completions file. I plan on working on it as soon as I have some spare time.

**Comment by shyiko** [comment]
`,,,` yields `_commacd_backward_forward:3: bad pattern`.

**Comment by shyiko** [comment]
FYI, [there is a test suite](https://github.com/shyiko/commacd/blob/master/shpec/commacd_shpec.sh). It should work under the ZSH too, though I obviously haven't tried it :)

**Comment by qfjp** [comment]
Ah, that helps, I was about to ask if you had any test cases.

Looks like I'm passing all test cases but two, since zsh arrays are indexed from 1 instead of 0. If you change the tests to echo 1 all tests pass (old zsh and new). I'll let you know if I get around to fixing the completion.

**Comment by shyiko** [comment]
Closing in favor of #16 (merged into [commacd@1.0.0](https://github.com/shyiko/commacd/blob/master/CHANGELOG.md#100---2019-02-03)). 
Thank you for all the effort nonetheless, @qfjp. 🙇

**Pull request closed without merging**
